#ifndef __DEFINES_H__
#define __DEFINES_H__

#define WRITEBYTE(WORD,BITSTARTPOS,BYTE) WORD=((WORD&~(0xFF<<BITSTARTPOS))|(BYTE<<BITSTARTPOS))

#define READBIT(WORD,BIT) ((WORD>>BIT)&1)

#define WRITEBIT(WORD,BITPOS,BITLEVEL) WORD=((WORD&~(1<<BITPOS))|(BITLEVEL<<BITPOS))

#define SETBIT(WORD,BIT) (WORD|=(1<<BIT))

#define CLRBIT(WORD,BIT) (WORD&=~(1<<BIT))

#define CPLBIT(WORD,BITPOS) (WORD^=(1<<BITPOS))

#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT) DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))

#define READNIBBLE(WORD,SBITPOS) ((WORD>>SBITPOS)&15)

#define WRITEPAIRBIT(WORD,BITPAIRPOS,PAIRBIT) WORD=(WORD&(~(3<<BITPAIRPOS)))|(PAIRBIT<<BITPAIRPOS)

#define WRITENIBBLE(WORD,SBITPOS,NIBBLE) WORD=(WORD&(~(15<<SBITPOS)))|(NIBBLE<<SBITPOS)

#define READWRITEBIT2(WORD,WBIT,RBIT) WORD=(WORD&(~(1<<WBIT)))|(((WORD>>RBIT)&1)<<WBIT)

#define CFGPIN(WORD,PIN,FUNC) WORD=(PIN<16)?((WORD&(~(3<<(PIN*2))))|(FUNC<<(PIN*2))):((WORD&(~(3<<((PIN-16)*2))))|(FUNC<<((PIN-16)*2)))


#endif
